name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, secrets-implementation ]
  pull_request:
    branches: [ main, secrets-implementation ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install requirements
        run: pip install -U pandas attrs twarc twarc_csv

      - name: execute py script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python src/extract.py
